#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cpan
# autospec version: v2
# autospec commit: e661f3a625d7
#
Name     : perl-XML-XPath
Version  : 1.48
Release  : 33
URL      : https://cpan.metacpan.org/authors/id/M/MA/MANWAR/XML-XPath-1.48.tar.gz
Source0  : https://cpan.metacpan.org/authors/id/M/MA/MANWAR/XML-XPath-1.48.tar.gz
Summary  : 'Parse and evaluate XPath statements.'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-XML-XPath-bin = %{version}-%{release}
Requires: perl-XML-XPath-license = %{version}-%{release}
Requires: perl-XML-XPath-man = %{version}-%{release}
Requires: perl-XML-XPath-perl = %{version}-%{release}
BuildRequires : buildreq-cpan
BuildRequires : perl(Path::Tiny)
BuildRequires : perl(XML::Parser)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
NAME
XML::XPath - a set of modules for parsing and evaluating XPath
statements
DESCRIPTION

%package bin
Summary: bin components for the perl-XML-XPath package.
Group: Binaries
Requires: perl-XML-XPath-license = %{version}-%{release}

%description bin
bin components for the perl-XML-XPath package.


%package dev
Summary: dev components for the perl-XML-XPath package.
Group: Development
Requires: perl-XML-XPath-bin = %{version}-%{release}
Provides: perl-XML-XPath-devel = %{version}-%{release}
Requires: perl-XML-XPath = %{version}-%{release}

%description dev
dev components for the perl-XML-XPath package.


%package license
Summary: license components for the perl-XML-XPath package.
Group: Default

%description license
license components for the perl-XML-XPath package.


%package man
Summary: man components for the perl-XML-XPath package.
Group: Default

%description man
man components for the perl-XML-XPath package.


%package perl
Summary: perl components for the perl-XML-XPath package.
Group: Default
Requires: perl-XML-XPath = %{version}-%{release}

%description perl
perl components for the perl-XML-XPath package.


%prep
%setup -q -n XML-XPath-1.48
cd %{_builddir}/XML-XPath-1.48

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} -I. Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/perl-XML-XPath
cp %{_builddir}/XML-XPath-%{version}/LICENSE %{buildroot}/usr/share/package-licenses/perl-XML-XPath/c5cff293e3705e11e692c1b57900e4bd96436630 || :
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/xpath

%files dev
%defattr(-,root,root,-)
/usr/share/man/man3/XML::XPath.3
/usr/share/man/man3/XML::XPath::Boolean.3
/usr/share/man/man3/XML::XPath::Builder.3
/usr/share/man/man3/XML::XPath::Function.3
/usr/share/man/man3/XML::XPath::Literal.3
/usr/share/man/man3/XML::XPath::Node.3
/usr/share/man/man3/XML::XPath::Node::Attribute.3
/usr/share/man/man3/XML::XPath::Node::Comment.3
/usr/share/man/man3/XML::XPath::Node::Element.3
/usr/share/man/man3/XML::XPath::Node::Namespace.3
/usr/share/man/man3/XML::XPath::Node::PI.3
/usr/share/man/man3/XML::XPath::Node::Text.3
/usr/share/man/man3/XML::XPath::NodeSet.3
/usr/share/man/man3/XML::XPath::Number.3
/usr/share/man/man3/XML::XPath::PerlSAX.3
/usr/share/man/man3/XML::XPath::XMLParser.3

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/perl-XML-XPath/c5cff293e3705e11e692c1b57900e4bd96436630

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/xpath.1

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/*
